### ISSUE TITLE
Leapr - misc errors at certain temperatures

### ISSUE THREAD

**Issue by Camden-Blake** [njoy/NJOY2016#331]
# Overview

When using the leapr module to generate TSL values for Fe_056, Al_027, and Be-metal at specific temperatures, different errors are thrown.  Specifically, Fe_056 at 717-721 K, Al_027 at 180 and 190 K, and Be-metal at 423 K.  There may be more temperatures, these are just the ones I have found so far.

Below are some samples of the files (one that works and one that passes an error) and the errors produced.

# Fe_056

## 717K
```
njoy 2016.74  12Jan24                                       03/12/24 15:24:08
 *****************************************************************************

 leapr...                                                                 0.0s
free(): invalid size

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0xabe57023970 in ???
#1  0xabe57022ad5 in ???
#2  0xabe56c4251f in ???
#3  0xabe56c969fc in pthread_kill
#4  0xabe56c42475 in raise
#5  0xabe56c287f2 in abort
#6  0xabe56c89675 in ???
#7  0xabe56ca0cfb in ???
#8  0xabe56ca2a53 in ???
#9  0xabe56ca5452 in __libc_free
#10  0xabe575bb63a in __leapm_MOD_leapr
#11  0x61621675073c in MAIN__
#12  0x6162167502ce in main
Aborted (core dumped)
```

## 718K

```
njoy 2016.74  12Jan24                                       03/12/24 15:33:38
 *****************************************************************************

 leapr...                                                                 0.0s
double free or corruption (out)
...
```

## 719K

```
njoy 2016.74  12Jan24                                       03/12/24 15:35:08
 *****************************************************************************

 leapr...                                                                 0.0s
munmap_chunk(): invalid pointer
...
```

[026_Fe_056_717K.txt](https://github.com/njoy/NJOY2016/files/14577641/026_Fe_056_717K.txt)
[026_Fe_056_716K.txt](https://github.com/njoy/NJOY2016/files/14577642/026_Fe_056_716K.txt)

# Al_027

Similar behavior to Fe_056 with free(): invalid size and munmap_chunk(): invalid pointer errors.

[013_Al_027_181K.txt](https://github.com/njoy/NJOY2016/files/14577644/013_Al_027_181K.txt)
[013_Al_027_180K.txt](https://github.com/njoy/NJOY2016/files/14577645/013_Al_027_180K.txt)

# Be-metal

Similar behavior to Fe_056 with munmap_chunk(): invalid pointer error.

[Be-metal_422K.txt](https://github.com/njoy/NJOY2016/files/14577646/Be-metal_422K.txt)
[Be-metal_423K.txt](https://github.com/njoy/NJOY2016/files/14577647/Be-metal_423K.txt)

**Comment by whaeck** [comment]
Fun. Probably some array size issues. I'll have a look once I get some time.
