### ISSUE TITLE
Binary gendf file crashes mf35 errorr run

### ISSUE THREAD

**Issue by whaeck** [njoy/NJOY2016#77]
When using a binary gendf file coming out of groupr, errorr segfaults when processing the mf35 covariances:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Backtrace for this error:
#0  0x2b61f2e8926f in ???
#1  0x2b61a12f220c in spcint
	at /users/wim/NJOY2016/src/errorr.f90:2673
Segmentation fault

When using an ascii gendf file, there appears to be no issue at all. The following inputs illustrate the issue (the input endf tape is U235 from ENDF/B-VII.1):
[errorr-ascii.txt](https://github.com/njoy/NJOY2016/files/1881021/errorr-ascii.txt)
[errorr-binary.txt](https://github.com/njoy/NJOY2016/files/1881022/errorr-binary.txt)

**Comment by whaeck** [comment]
This issue has been addressed in Pull request #81.
